CREATE TABLE LND_EMPLOYEE_REGISTRATION (
CANDIDATE_REGISTRATION_NUMBER int NOT NULL AUTO_INCREMENT,
FIRST_NAME varchar(255) ,
MIDDLE_NAME varchar(255) ,
LAST_NAME varchar(255) ,
GENDER varchar(255) ,
MARITAL_STATUS varchar(255) ,
EDUCATION_DEGREE varchar(255) ,
PRIMARY_SKILLS varchar(255) ,
SECONDARY_SKILLS varchar(255) ,
AADHAR_NUMBER varchar(255) ,
MOBILE_NUMBER varchar(255) ,
DATE_OF_BIRTH varchar(255) ,
ADDRESS_LINE1 varchar(255) ,
ADDRESS_LINE2 varchar(255) ,
CITY varchar(255) ,
STATE varchar(255) ,
ZIP_CODE varchar(255) ,
PREVIOUS_EXPERIENCE varchar(255),
YEARS_OF_EXPERIENCE varchar(255),
PREFERENCE varchar(255),
PREFERRED_LOCATION varchar(255),
CREATE_TS datetime  DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (CANDIDATE_REGISTRATION_NUMBER)
);

CREATE TABLE LND_COMPANY_REGISTRATION (
COMPANY_REGISTRATION_NUMBER int NOT NULL AUTO_INCREMENT,
CORPORATE_NAME varchar(255) ,
CONTACT_PERSON_FIRST_NAME varchar(255) ,
CONTACT_PERSON_MIDDLE_NAME varchar(255) ,
CONTACT_PERSON_LAST_NAME varchar(255) ,
COMPANY_PAN_CARD varchar(255) ,
COMPANY_AADHAR_NUMBER varchar(255) ,
CONTACT_NUMBER varchar(255) ,
ADDRESS_LINE1 varchar(255) ,
ADDRESS_LINE2 varchar(255) ,
CITY varchar(255) ,
STATE varchar(255) ,
COUNTRY varchar(255) ,
ZIP_CODE varchar(255) ,
CREATE_TS datetime  DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (COMPANY_REGISTRATION_NUMBER)
);

CREATE TABLE LND_JOB_POSTINGS (
JOB_ID int NOT NULL AUTO_INCREMENT,
COMPANY_REGISTRATION_NUMBER varchar(255),
CORPORATE_NAME varchar(255) ,
JOB_DESCRIPTION varchar(255) ,
REQUIRED_SKILLS varchar(255) ,
WORK_EXPERIENCE varchar(255) ,
CONTACT_NUMBER varchar(255) ,
PREFERENCE varchar(255),
JOB_LOCATION_CITY varchar(255) ,
JOB_LOCATION_STATE varchar(255),
CREATE_TS datetime  DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (JOB_ID)
);